name: terrava
description: "Terrava — map-first real estate discovery"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.3.0
  cached_network_image: ^3.4.1
  dio: ^5.11.1
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.5.1
  flutter_riverpod: ^3.3.2
  flutter_secure_storage: ^10.3.1
  geolocator: ^14.0.2
  google_fonts: ^6.3.2
  image_picker: ^1.2.2
  mapbox_maps_flutter: ^2.30.0
  socket_io_client: ^3.1.6

dev_dependencies:
  auto_route_generator: ^10.2.6
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
